CROSS_COMPILE=
CC=$(CROSS_COMPILE)gcc
OBJCP=$(CROSS_COMPILE)objcopy
LD=$(CROSS_COMPILE)ld
OBJDMP=$(CROSS_COMPILE)objdump
CFLAGS=-O3 -D_GNU_SOURCE

all: mksunxiboot

mksunxiboot: mksunxiboot.c

clean:
	rm -f mksunxiboot


